### ISSUE TITLE
Not found?

### ISSUE THREAD

**Issue by Davvalito** [backup-manager/laravel-5#1]
Hi,
When trying to install through composer, I am getting the following error:
"The requested package backup-manager/laravel-5 could not be found in any version, there may be a typo in the package name."

**Comment by ShawnMcCool** [comment]
Yes, as you can see the repository is empty. This is part of me moving the backup-manager from the heybigname organization to the backup-manager organization. Currently, I'm making this work https://github.com/backup-manager/laravel-4 then I'm going to update the backup-manager to not have a laravel-4 driver built into the repository. Afterwards, I'll be filling this one out.
